ALTER TABLE games RENAME COLUMN game_id TO id;
ALTER TABLE games ADD COLUMN IF NOT EXISTS public_code TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS seed TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS ruleset_json JSONB;
ALTER TABLE games ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE games ADD COLUMN IF NOT EXISTS dealer_seat INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS completed_at BIGINT;

ALTER TABLE game_players ADD COLUMN IF NOT EXISTS seat INTEGER;
ALTER TABLE game_players ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE game_players ADD COLUMN IF NOT EXISTS guest_name TEXT;
ALTER TABLE game_players ADD COLUMN IF NOT EXISTS player_type TEXT;
ALTER TABLE game_players ADD COLUMN IF NOT EXISTS ai_difficulty TEXT;
